### ISSUE TITLE
Frontend: Toolbar: Narrow window hides elements

### ISSUE THREAD

**Issue by chr5tphr** [virelay/virelay#15]
- The upper tool bar (Choice of analysis, color-map, sharing...) is very wide, and is not very accessible with a narrow browser window.
- It would much easier to use with a narrow window when the elements in the tool bar would be allowed to start a new row.

<details>
  <summary>Wide Window</summary>
  
  ![image](https://user-images.githubusercontent.com/15217558/159765972-0dca27d9-d3ee-452f-bcec-7c607e3ec961.png)

</details>

<details>
  <summary>Narrow Window</summary>
  
  ![image](https://user-images.githubusercontent.com/15217558/159766129-2277d99c-3b6f-4164-a9b6-466fc3994f9a.png)
</details>

**Comment by lecode-official** [comment]
We could do that, but that would in turn reduce the vertical space. I made the toolbar horizontally scrollable for this exact reason. Granted, this is not very user-friendly, but on the other hand, some degradation in usability should be expected when decreasing the window size.

I think, as long as it is usable when the window covers half the screen (having the window docked to one side of the screen is a fairly common use case), it should be fine. I'll have a look at it and if the usability is bad in this case, I will think of a solution.

**Comment by lecode-official** [comment]
I have decreased the size of the horizontal scroll bar of the toolbar, so that it takes up less space. Also, the toolbar (and the selected attributions pane) can now be scrolled horizontally with the mouse scroll wheel. This improves the UX of the toolbar. I still believe that breaking the toolbar over multiple lines would be the greater evil, as it would dramatically increase the toolbar height and leave less space for the embedding viewer.

I'll close this ticket for now. If anyone has a better idea, then please reopen it.
